/** @format */

import Head from 'next/head';
import React, { useEffect } from 'react';
import { Box } from '@mui/system';
import Layout from '../components/Layout';
import { Context } from '../ContextComp';
import { useMediaQuery } from '@mui/material';

const MainLayout = (props) => {
	const { mainPlacesOutput } = props;
	const maxWidth900 = useMediaQuery('(max-width:900px)');
	const maxWidth600 = useMediaQuery('(max-width:600px)');

	return (
		<Context.Provider
			value={{
				maxWidth900,
				maxWidth600
			}}>
			<Box sx={{ position: 'relative' }}>
				<Layout>
					<>
						<Head>
							<title>Arctic Nextjs blog</title>
							<meta name='description' content='Generated by create next app' />
							<link rel='icon' href='/favicon.ico' />
						</Head>
						{props.children}
					</>
				</Layout>
			</Box>
		</Context.Provider>
	);
};

export default MainLayout;
